spring:
  application:
    name: resource-server-pkce-flow
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-pkce-realm

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG