spring:
  application:
    name: resource-server-authentication-code-flow
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-authentication-code-flow-realm

server:
  port: 8086

logging:
  level:
    org.springframework.security: DEBUG